server:
  port: 8081
  servlet:
    context-path: "/spring-ai-mcp-server1"

spring:
  application:
    name: "spring-ai-mcp-server1"
  threads:
    virtual:
      enabled: true
  ai:
    mcp:
      server:
        enabled: true
        name: "spring-ai-mcp-server1"
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: "/mcp/message"
        sse-endpoint: "/sse"

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{x_request_id:-no_request_id} %m %wEx %n'
  level:
    web: INFO
    org:
      springframework:
        ai: INFO

logback-access:
  pattern: '%t{yyyy-MM-dd HH:mm:ss.SSS} ACCESS_LOG %D %B %s %i{x-forwarded-for} %reqAttribute{x_request_id} %m %U%q'

logback.access:
  enabled: "${ACCESS_LOG_ENABLED:true}"
  tee-filter:
    enabled: "${ACCESS_TEE_LOG_ENABLED:true}"